# **Question 1**

In [61]:
import numpy as np
import time

In [60]:

# Task 1:
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)



Empty Array (2x2):
[[4.80581729e-310 0.00000000e+000]
 [2.10077583e-312 5.73116149e-322]]


In [3]:
# Task 2:
ones_array = np.ones((4, 2))
print("\nAll-Ones Array (4x2):")
print(ones_array)


All-Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# Task 3:
fill_value_array = np.full((3, 3), 7)  # Shape (3x3), filled with value 7
print("\nArray filled with 7 (3x3):")
print(fill_value_array)


Array filled with 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
# Task 4:
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array (same shape as given_array):")
print(zeros_like_array)



Zeros Array (same shape as given_array):
[[0 0]
 [0 0]]


In [6]:
# Task 5:
ones_like_array = np.ones_like(given_array)
print("\nOnes Array (same shape as given_array):")
print(ones_like_array)


Ones Array (same shape as given_array):
[[1 1]
 [1 1]]


In [7]:
# Task 6:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array from list:")
print(numpy_array)


Converted NumPy Array from list:
[1 2 3 4]


# **Question 2**

In [8]:
# Task 1:
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(array_10_to_49)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# Task 2:
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)


3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Task 3:
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
# Task 4:
x = np.random.random(30)
mean = x.mean()

print("array given: ", x)
print("Mean  : ", mean)

array given:  [0.90811492 0.78370423 0.4123577  0.42099048 0.82350709 0.68986574
 0.93808476 0.11620095 0.17182478 0.81585089 0.76257638 0.9417421
 0.17526379 0.70606265 0.93112633 0.70726053 0.49977829 0.82536016
 0.04534475 0.53913155 0.19537468 0.42208625 0.66524593 0.0621545
 0.81434835 0.81451612 0.12983516 0.04882618 0.46149703 0.09380352]
Mean  :  0.5307278592315888


In [12]:
# Task 5:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:")
print(random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


10x10 Random Array:
[[0.84904808 0.64409505 0.62901002 0.50957695 0.99554186 0.195443
  0.15175639 0.59643966 0.39292438 0.80360963]
 [0.81467078 0.95749823 0.71598431 0.4387205  0.93617936 0.10152464
  0.79692915 0.17788495 0.27566096 0.18901611]
 [0.11985787 0.0202547  0.3367508  0.49633676 0.09831403 0.45955525
  0.90810302 0.24627698 0.95829555 0.1068559 ]
 [0.84598576 0.90230682 0.60226465 0.58252116 0.52990792 0.0813442
  0.70151753 0.21330865 0.84304563 0.46056959]
 [0.03083794 0.19683333 0.78587391 0.45501198 0.62270547 0.73568194
  0.87674455 0.41894599 0.24592343 0.78876204]
 [0.77852126 0.51486674 0.89585028 0.42368485 0.68029227 0.02085431
  0.42537727 0.3329768  0.58855072 0.3137931 ]
 [0.13836411 0.4846756  0.71475892 0.27037556 0.66107992 0.34375991
  0.97444594 0.1540244  0.99635333 0.04097585]
 [0.89188546 0.21255399 0.14070892 0.40653385 0.23622301 0.02316869
  0.49909582 0.9069485  0.55663435 0.05884918]
 [0.17897668 0.00287705 0.11168322 0.78769594 0.73930451 0.092

In [13]:
# Task 6:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element Replaced by 1:")
print(zero_array)


Zero Array with 5th Element Replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [41]:
# Task 7:
b=np.array([1,2,0,0,4,0])
rev=b[::-1]
print("Original: ", b)
print("reversed: ", rev)

Original:  [1 2 0 0 4 0]
reversed:  [0 4 0 0 2 1]


In [42]:
# Task 8:
b=np.zeros((5,5),dtype=int)
b[0,:]=1 #top
b[-1,:]=1 #bottom
b[:,0]=1 #left
b[:,-1]=1 #right
print("1 on border and 0 inside : ",b)


1 on border and 0 inside :  [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [16]:
# Task 9:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)




8x8 Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## **Question 3**

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [24]:
# Task 1:
addition = x + y
print("Addition of x and y:")
print(addition)

Addition of x and y:
[[ 6  8]
 [10 12]]


In [26]:
# Task 2:
subtraction = x - y
print("\nSubtraction of x and y:")
print(subtraction)


Subtraction of x and y:
[[-4 -4]
 [-4 -4]]


In [31]:
# Task 3:
multiplication = w * 2
print("\nMultiplication of x with 3:")
print(multiplication)


Multiplication of x with 3:
[22 24]


In [30]:
# Task 4:
squared = y ** 2
print("\nSquare of each element in x:")
print(squared)


Square of each element in x:
[[25 36]
 [49 64]]


In [36]:
# Task 5:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y
print("\nDot Product are:")
print(f"Dot product of v and w: {dot_vw}")
print(f"Dot product of x and v: {dot_xv}")
print(f"Dot product of x and y: \n{dot_xy}")


Dot Product are:
Dot product of v and w: 219
Dot product of x and v: [29 67]
Dot product of x and y: 
[[19 22]
 [43 50]]


In [37]:
# Task 6:
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.vstack((v, w)).T
print("\nConcatenation:")
print("Concatenate x and y along rows:")
print(concat_xy_row)
print("Concatenate v and w along columns:")
print(concat_vw_column)



Concatenation:
Concatenate x and y along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 11]
 [10 12]]


In [44]:
# Task 7:

result = np.concatenate((x, x3))
print("Concatenation result:\n", result)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)

***x and x3 have different dimension***

# **Question 4**

Task 1

In [45]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [49]:
# Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print(identity)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [50]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)
print("\nAB == BA:", np.array_equal(AB, BA))



AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB == BA: False


In [51]:
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:")
print(AB_T)
print("\nB^T . A^T:")
print(BT_AT)
print("\n(AB)^T == B^T . A^T:", np.array_equal(AB_T, BT_AT))



(AB)^T:
[[23 51]
 [13 29]]

B^T . A^T:
[[23 51]
 [13 29]]

(AB)^T == B^T . A^T: True


Task 2

In [57]:
A1=np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B1=np.array([-1,-3,9])


In [58]:
A_inverse=np.linalg.inv(A1)
x=np.dot(A_inverse,B1)
print( A1)
print( B1)
print( A_inverse)
print( x)


[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
[-1 -3  9]
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
[ 2.  1. -2.]


# **Question 5**

In [62]:
def measure_time(func, *args):
    start_time = time.time()
    result = func(*args)
    end_time = time.time()
    return result, end_time - start_time

Task 1

In [63]:
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.array(list1)
array2 = np.array(list2)

def list_addition(list1, list2):
    return [list1[i] + list2[i] for i in range(len(list1))]

_, time_list_add = measure_time(list_addition, list1, list2)

_, time_numpy_add = measure_time(np.add, array1, array2)

print(f"Element-wise Addition:")
print(f"Python Lists Time: {time_list_add:.6f} seconds")
print(f"NumPy Arrays Time: {time_numpy_add:.6f} seconds\n")

Element-wise Addition:
Python Lists Time: 0.153364 seconds
NumPy Arrays Time: 0.007979 seconds



Task 2

In [65]:
def list_multiplication(list1, list2):
    return [list1[i] * list2[i] for i in range(len(list1))]
_, time_list_mul = measure_time(list_multiplication, list1, list2)
_, time_numpy_mul = measure_time(np.multiply, array1, array2)
print(f"Element-wise Multiplication:")
print(f"Python Lists Time: {time_list_mul:.6f} seconds")
print(f"NumPy Arrays Time: {time_numpy_mul:.6f} seconds\n")


Element-wise Multiplication:
Python Lists Time: 0.125525 seconds
NumPy Arrays Time: 0.006476 seconds



Task 3

In [ ]:
def list_dot_product(list1, list2):
    return sum(list1[i] * list2[i] for i in range(len(list1)))

_, time_list_dot = measure_time(list_dot_product, list1, list2)

_, time_numpy_dot = measure_time(np.dot, array1, array2)

print(f"Dot Product:")
print(f"Python Lists Time: {time_list_dot:.6f} seconds")
print(f"NumPy Arrays Time: {time_numpy_dot:.6f} seconds\n")


size_matrix = 1000
list_matrix1 = [[i for i in range(size_matrix)] for _ in range(size_matrix)]
list_matrix2 = [[i for i in range(size_matrix)] for _ in range(size_matrix)]
array_matrix1 = np.array(list_matrix1)
array_matrix2 = np.array(list_matrix2)


def list_matrix_multiplication(matrix1, matrix2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
    return result

_, time_list_matrix_mul = measure_time(list_matrix_multiplication, list_matrix1, list_matrix2)


_, time_numpy_matrix_mul = measure_time(np.dot, array_matrix1, array_matrix2)

print(f"Matrix Multiplication:")
print(f"Python Lists Time: {time_list_matrix_mul:.6f} seconds")
print(f"NumPy Arrays Time: {time_numpy_matrix_mul:.6f} seconds")

Dot Product:
Python Lists Time: 0.152254 seconds
NumPy Arrays Time: 0.002635 seconds

